//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOU2_Ershov_ED
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoparkEntities : DbContext
    {
        public AutoparkEntities()
            : base("name=AutoparkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreement> Agreement { get; set; }
        public virtual DbSet<Car_make> Car_make { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Service_list> Service_list { get; set; }
        public virtual DbSet<Service_point> Service_point { get; set; }
        public virtual DbSet<Status_list> Status_list { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Storage_car> Storage_car { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
