//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOU2_Ershov_ED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Agreement = new HashSet<Agreement>();
            this.Service_point = new HashSet<Service_point>();
        }
    
        public int id_car { get; set; }
        public Nullable<int> id_color { get; set; }
        public string Registration_number { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_storage { get; set; }
        public Nullable<int> id_car_make { get; set; }
        public Nullable<System.DateTime> Release_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agreement> Agreement { get; set; }
        public virtual Car_make Car_make { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Status_list Status_list { get; set; }
        public virtual Storage_car Storage_car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_point> Service_point { get; set; }
    }
}
